## 3.1 선형회귀

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.init as init

In [3]:
import plotly

In [24]:
device = torch.device("cuda:0")

In [40]:
# 노이즈가 추가된 데이터 생성
num_data = 1000
num_epoch = 100

x = init.uniform_(torch.Tensor(num_data, 1), -10, 10)
noise = init.normal_(torch.FloatTensor(num_data, 1), std=1)
y = 2*x + 3
y_noise = y + noise

In [47]:
# 선형 모델 구현
linear_model = nn.Linear(1, 1)
loss_func = nn.MSELoss()

# 옵티마이저
optimizer = optim.SGD(linear_model.parameters(), lr=0.001)
label = y_noise

In [49]:
print(linear_model.weight)
print(linear_model.bias)
print(linear_model.weight.grad)
print(linear_model.bias.grad)

Parameter containing:
tensor([[0.6637]], requires_grad=True)
Parameter containing:
tensor([0.3201], requires_grad=True)
None
None


In [42]:
# 학습
for i in range(num_epoch):
    optimizer.zero_grad() # 옵티마이저의 그래디언트를 0으로 초기화
    output = linear_model(x) # 모델을 통해 값을 예측
    loss = loss_func(output, label) # 정답 데이터와 예측 값과의 차이를 통해 손실함수 계산
    print(loss.item())
    loss.backward() # 자동미분을 통해 가중치에 대한 그래디언트 계산 calculate gradient
    optimizer.step() # 계산한 그래디언트를 통해 가중치 업데이트 w = w - alpha * gradient

    if i % 10 == 0:
        print(loss.data)

42.574405670166016
tensor(42.5744)
38.29449462890625
34.553863525390625
31.284067153930664
28.42535972595215
25.92557144165039
23.739164352416992
21.826379776000977
20.152494430541992
18.687204360961914
17.4040470123291
tensor(17.4040)
16.279911041259766
15.294633865356445
14.430606842041016
13.672447204589844
13.006738662719727
12.421758651733398
11.907275199890137
11.454353332519531
11.055197715759277
10.70299243927002
tensor(10.7030)
10.391801834106445
10.116425514221191
9.872336387634277
9.655576705932617
9.46269416809082
9.290668487548828
9.136870384216309
8.99899673461914
8.875044822692871
8.763260841369629
tensor(8.7633)
8.662113189697266
8.570266723632812
8.486553192138672
8.409955024719238
8.33958625793457
8.274663925170898
8.214519500732422
8.158553123474121
8.106249809265137
8.057158470153809
tensor(8.0572)
8.010887145996094
7.967087268829346
7.9254631996154785
7.885749340057373
7.847719192504883
7.811171531677246
7.775930404663086
7.741842269897461
7.70877742767334
7.676616

In [43]:
print(linear_model.weight)
print(linear_model.bias)

Parameter containing:
tensor([[1.9974]], requires_grad=True)
Parameter containing:
tensor([0.7080], requires_grad=True)


# 퀴즈 (Easy)  
1) 위 선형회귀모델에서 하이퍼파라미터의 종류는 뭐가 있을까요?  
2) 하이퍼파라미터를 조정해서 모델의 가중치와 편향이 정답에 가깝도록 학습시켜보세요

## 3.2 다중선형회귀

In [81]:
num_data = 1000
num_epoch = 1000

x = init.uniform_(torch.Tensor(10, 3), -10, 10)
noise = init.normal_(torch.FloatTensor(10, 1), std=1)
weights = torch.tensor([2., 3., 1.])
print(x.matmul(weights).shape)
y = x.matmul(weights) + -1
y = y.unsqueeze(1)
print(f"y.shape {y.shape}")
y_noise = y + noise

torch.Size([10])
y.shape torch.Size([10, 1])


In [84]:
# 다중회귀 모델 구현
multi_model = nn.Linear(3, 1)
loss_func = nn.MSELoss()

# 옵티마이저
optimizer = optim.SGD(multi_model.parameters(), lr=0.001)
label = y_noise

In [85]:
# 학습
for i in range(num_epoch):
    optimizer.zero_grad() # 옵티마이저의 그래디언트를 0으로 초기화
    output = multi_model(x) # 모델을 통해 값을 예측
    loss = loss_func(output, label) # 정답 데이터와 예측 값과의 차이를 통해 손실함수 계산
    print(loss.item())
    loss.backward() # 자동미분을 통해 가중치에 대한 그래디언트 계산 calculate gradient
    optimizer.step() # 계산한 그래디언트를 통해 가중치 업데이트 w = w - alpha * gradient

    if i % 10 == 0:
        print(loss.data)

155.5640411376953
tensor(155.5640)
147.62271118164062
140.11184692382812
133.00595092773438
126.28114318847656
119.91514587402344
113.8872299194336
108.17790222167969
102.76905822753906
97.64363861083984
92.78575134277344
tensor(92.7858)
88.1804428100586
83.81367492675781
79.6723403930664
75.7440414428711
72.01719665527344
68.4808578491211
65.1247787475586
61.93927764892578
58.915260314941406
56.04413986206055
tensor(56.0441)
53.317840576171875
50.72871780395508
48.26959991455078
45.933692932128906
43.71456527709961
41.6061897277832
39.60283660888672
37.6990966796875
35.88986587524414
34.17029571533203
tensor(34.1703)
32.53582763671875
30.98212242126465
29.505090713500977
28.10085678100586
26.765731811523438
25.496248245239258
24.289108276367188
23.14118003845215
22.04950714111328
21.011281967163086
tensor(21.0113)
20.023839950561523
19.084646224975586
18.191320419311523
17.341571807861328
16.533252716064453
15.764312744140625
15.032809257507324
14.336898803710938
13.674817085266113
13

0.619200587272644
0.6191832423210144
0.6191659569740295
0.6191491484642029
0.6191322207450867
tensor(0.6191)
0.6191147565841675
0.6190977096557617
0.6190805435180664
0.6190627217292786
0.6190460920333862
0.6190294027328491
0.6190123558044434
0.6189951300621033
0.6189787983894348
0.6189627647399902
tensor(0.6190)
0.6189447045326233
0.6189284324645996
0.6189121007919312
0.6188955903053284
0.618878185749054
0.6188624501228333
0.6188454627990723
0.6188297271728516
0.6188126802444458
0.6187968850135803
tensor(0.6188)
0.6187806129455566
0.6187629103660583
0.6187472939491272
0.6187314987182617
0.6187146902084351
0.6186994910240173
0.6186832785606384
0.6186670064926147
0.6186505556106567
0.6186342835426331
tensor(0.6186)
0.618618369102478
0.6186028122901917
0.6185871958732605
0.6185712814331055
0.618556022644043
0.6185387372970581
0.618524432182312
0.6185077428817749
0.618491530418396
0.6184766888618469
tensor(0.6185)
0.6184611320495605
0.6184448003768921
0.6184300184249878
0.6184139251708984


In [87]:
print(multi_model.weight)
print(multi_model.bias)

Parameter containing:
tensor([[1.9208, 2.9586, 0.9299]], requires_grad=True)
Parameter containing:
tensor([-0.4714], requires_grad=True)


# 퀴즈 (Easy)  
1) 하이퍼파라미터를 조정해서 모델의 가중치와 편향이 정답에 가깝도록 학습시켜보세요