 ## 5. 텐서의 연산

파이토치에서 다루는 모든 벡터, 행렬, 텐서들에 대해서  
덧셈, 뺄셈, 내적, 외적을 할 수 있습니다.  

In [1]:
import torch as th
from torch import tensor

In [5]:
# in place operation : 별도의 메모리 할당 없이 텐서를 조작하는 연산

vec1 = tensor([1, 2, 3])
print(vec1.shape)
unsq_vec1 = vec1.unsqueeze(0)
print(unsq_vec1.shape)
vec1.unsqueeze_(0)
print(vec1.shape)


torch.Size([3])
torch.Size([1, 3])
torch.Size([1, 3])


In [3]:
vec1 = tensor([1, 2, 3])
vec2 = tensor([4, 5, 6])

In [5]:
# 벡터의 dot product를 위해서는 torch.dot 메소드 또는 tensor.dot 메소드를 사용합니다.
vec3 = vec1.dot(vec2) # 1 * 4 + 2 * 5 + 3 * 6
print(vec3)

tensor(32)


In [6]:
# 하이퍼 네트워크 : 딥러닝 모델의 가중치를 출력으로 하는 딥러닝 모델

crosse_vec = th.cross(vec1, vec2) # 벡터의 길이가 3차원이어야 한다.
print(crosse_vec)

tensor([-3,  6, -3])


In [9]:
# * : 에스터리스크(asterisk) 이 기호는 element wise product를 수행합니다.
vec4 = vec1 * vec2
print(vec4) # [4, 10, 18]

# 모든 텐서는 에스터리스크 기호를 통해 원소곱을 수행할 수 있다. 
mat1 = tensor([[1, 2], 
              [3, 4]])
mat2 = tensor([[5, 6], 
              [7, 8]])
print(mat1 * mat2) # 5, 12, 21, 32

tensor([ 4, 10, 18])
tensor([[ 5, 12],
        [21, 32]])


In [10]:
# at sign @ : 골뱅이 기호는 행렬곱을 수행하게 됩니다. 
# matmul 함수를 통해서도 행렬곱을 계산할 수 있다. 

mat4 = mat1 @ mat2
mat5 = mat1.matmul(mat2)
print(mat4)
print(mat5)




tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])


In [12]:
ten1 = tensor([[[1, 2], 
              [3, 4]],
                [[5, 6], 
              [7, 8]]])
ten2 = tensor([[[1, 2], 
              [3, 4]],
                [[5, 6], 
              [7, 8]]])

# @ 기호는 matmul 기능을 수행한다!
a = ten1.matmul(ten2)
b = ten1 @ ten2
print(a)
print(b)

tensor([[[  7,  10],
         [ 15,  22]],

        [[ 67,  78],
         [ 91, 106]]])
tensor([[[  7,  10],
         [ 15,  22]],

        [[ 67,  78],
         [ 91, 106]]])


## 6. 텐서 차원 조작  *** 중요!!! ***
딥러닝 모델에 데이터를 입력하기 위해 텐서의 차원을 정말 잘 다루어야 합니다.   
이때 차원을 조작하는 메소드로는 다음과 같습니다.
1) 차원 축소, 확장 :  squeeze(), unsqueeze()  
2) 차원 교환 : transpose(), permute() : 순서를 바꾸다. 역순으로도 바꿀 수 있음. 인풋에 따라 순서를 바꿈.     
3) 차원 조정 : flatten(), view() reshape()  
4) 텐서 합성 및 적재 : cat() stack()  

### 6.1 차원 축소, 확장 :  squeeze(), unsqueeze()  

In [19]:
# torch.ones(shape)를 통해 모든 값이 1인 텐서를 쉽게 만들 수 있다.
tensor_7d = th.ones([10, 32, 1, 1, 64, 64, 3])
tensor_7d = th.zeros([10, 32, 1, 1, 64, 64, 3])

# 차원의 모양을 일일히 입력하기 귀찮을 때 like가 붙은 메소드를 사용한다. 
tensor_7d2 = th.ones_like(tensor_7d)
tensor_7d3 = th.zeros_like(tensor_7d)
print(tensor_7d.shape)
print(tensor_7d2.shape)

# 항등행렬 .eye(shape)를 통해 만들 수 있다.
eye_tensor = th.eye(2)
print(eye_tensor.shape)

# 항등텐서도 있을까?? 궁금해지네요
v = th.randn(4)
diag_tensor = th.diag(v)

torch.Size([10, 32, 1, 1, 64, 64, 3])
torch.Size([10, 32, 1, 1, 64, 64, 3])
torch.Size([2, 2])


In [21]:
# torch.squeeze(axis) 함수는 차원의 크기가 1인 특정 축을 제거합니다. 
# axis 값이 없으면 크기가 1인 모든 축을 제거합니다. 

tensor_6d = tensor_7d.squeeze(axis=2) # shape에서 2번째 인덱스에 해당하는 축을 제거합니다. 
print(tensor_6d.shape) # [10, 32, 1, 64, 64, 3]
tensor_5d = tensor_7d.squeeze()
print(tensor_5d.shape) # [10, 32, 64, 64, 3]


torch.Size([10, 32, 1, 64, 64, 3])
torch.Size([10, 32, 64, 64, 3])


In [22]:
tensor_4d = th.ones([32, 3, 64, 64])
print(tensor_4d.shape)

torch.Size([32, 3, 64, 64])


In [27]:
# torch.unsqueeze(axis=m) : 차원의 크기가 1인 축을 m번째 인덱스에 추가합니다.
# axis 값이 없으면 어디에 추가될까요? -> 없으면 에러가 난다!!
# 퀴즈 : 0번째 인덱스에 잉여차원을 추가하세요
# 마지막 인덱스에 잉여차원을 추가하세요

# -1이 리스트에서 마지막 인덱스를 의미했는데 이는 토치에서도 똑같이 사용됩니다.
tensor_5d = tensor_4d.unsqueeze(0)
tensor_5d2 = tensor_4d.unsqueeze(4) # = -1 
print(tensor_5d.shape)
print(tensor_5d2.shape)


torch.Size([1, 32, 3, 64, 64])
torch.Size([32, 3, 64, 64, 1])


### 6.2 차원 교환 : transpose(), permute()  
위 메소드들은 주로 데이터를 변환할 때 많이 사용합니다.  


In [28]:
matrix = th.ones([2, 3])
print(matrix.shape)

torch.Size([2, 3])


In [33]:
# torch.transpose(input, dim0, dim1) 는 인풋 텐서의 두 차원을 교환합니다.
# torch.메소드를 호출하는 방법
# tensor.메소드를 호출하는 방법
transposed = th.transpose(matrix, 0, 1)
print(transposed.shape)
transposed2 = matrix.transpose(0, 1)
print(transposed2.shape)

tensor_4d = th.ones([4, 2, 6, 11])
# 퀴즈 : 0번째, 2번째 차원을 교환하세요
transposed_4d = tensor_4d.transpose(0, 2)
print(transposed_4d.shape) # 6, 2, 4, 11


torch.Size([3, 2])
torch.Size([3, 2])
torch.Size([6, 2, 4, 11])


In [42]:
# torch.permute() : transpose의 상위버전 메소드. 차원 축 순서를 원하는 대로 나열한다.
# 퀴즈 : tensor_4d의 차원축을 내림차순으로 정렬하세요.
# 텐서 순서의 조정은 직접 해야 한다.

permuted_4d = th.permute(tensor_4d, [3, 2, 0, 1])
print(permuted_4d.shape)
permuted_4d2 = th.permute(tensor_4d, (1, 0, 2, 3))
print(permuted_4d2.shape)


torch.Size([11, 6, 4, 2])
torch.Size([2, 4, 6, 11])


In [48]:
dic = tuple(tensor_4d.shape)
print(dic)
index_dic = {i: dic[i] for i in range(len(dic))}
print(a)

(4, 2, 6, 11)
{0: 4, 1: 2, 2: 6, 3: 11}
[(0, 4), (1, 2), (2, 6), (3, 11)]


matrix [[1, 2,], [3, 4]] -> [1, 2, 3, 4] -> reshape(2, 2)
### 6.3 차원 조정 : flatten(),  reshape(), view()  
위 세 가지 메소드는 주로 CNN 레이어에서 FC 레이어로 오고 갈 때 자주 사용합니다.  

In [51]:
# torch.flatten() 메소드는 텐서전체를 1차원 벡터로 변환합니다.
t = tensor([[[1, 2],
            [3, 4]],
           [[5, 6],
           [7, 8]]])
print(t.shape)

torch.Size([2, 2, 2])


In [52]:
flattened_t = th.flatten(t)
print(flattened_t)
print(flattened_t.shape)

tensor([1, 2, 3, 4, 5, 6, 7, 8])
torch.Size([8])


In [57]:
# 만약에 start_dim, end_dim이 주어지면 해당하는 차원부터 flatten합니다.
flattened_t2 = th.flatten(t, start_dim=2)
print(flattened_t2)
print(flattened_t2.shape)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
torch.Size([2, 2, 2])


In [59]:
import numpy as np

In [63]:
dic = tuple(tensor_4d.shape)
out = np.argsort(dic)
print(out)
a = th.ones([32, 16, 48])

[1 0 2 3]


In [58]:
# reshape() 메소드는 텐서를 원하는 모양을 가지도록 차원을 조정합니다.
# 단 이때, 각 차원의 총 형태가 원래의 차원과 일치해야 합니다. ex 8 -> 2, 2, 2 or 4, 2
t2 = th.arange(36)
t2.shape

torch.Size([36])

In [66]:
# 퀴즈 : t2의 모양을 (3, 3, 4)로 바꿔보세요
reshaped_t = t2.reshape(3, 3, 4)
print(reshaped_t.shape)

torch.Size([3, 3, 4])


In [70]:
# torch.view(-1, m, ...,) 차원의 크기가 아주 크고 복잡해서 reshape를 통해 일일히 계산하기 
t3 = th.arange(24940)
# 이때 -1 값이 들어가면 나머지 차원 축의 크기를 자동으로 계산합니다. 
# 퀴즈 : t3를 변환해서 두 개의 차원 축 값이 (5, 4, ?)인 텐서를 만드세요
viewed_t1 = t3.view(5, 4, -1)
viewed_t2 = t3.reshape(5, 4, -1)
print(viewed_t1.shape)

a = tensor([5.0, 1.0, 2.0, 4.0])

# in-place operation : 메모리에 새로 텐서를 할당하지 않고 기존 메모리에서 연산하는 방법
a = a.reshape(2, 2)
a

torch.Size([5, 4, 1247])


tensor([[5., 1.],
        [2., 4.]])

결국 view()랑 reshape랑 같은 역할을 한다!!   
그러나 gpu 메모리 내에서 메모리를 사용하는 방식이 다르다

### 6.4 텐서 합성 및 적재 : cat() stack()  
마지막으로 텐서를 합성하기 위해 cat()과 stack()을 활용합니다.  
cat() 함수는 모델 내부에서 다음 은닉층에 들어가는 텐서들을 조합하기 위해 주로 사용합니다.  

stack() 함수는 데이터를 쌓아서 미니배치를 구성할 때 주로 사용합니다.  

In [71]:
# torch.cat() 함수는 두 개 이상의 텐서 시퀀스들을 (특정 축을 기준으로) 합치게 됩니다. 
# 해당 텐서들의 차원은 반드시 같아야 합니다. 
vec1 = tensor([1, 2, 3])
vec2 = tensor([4, 5, 6])
vec3 = tensor([7, 8, 9])
vec4 = th.cat([vec1, vec2, vec3])
print(vec4)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [73]:
# stack() 메소드는 두 개 이상의 텐서들을 특정 축을 기준으로 쌓게 됩니다.
batch_vec = th.stack([vec1, vec2, vec3], dim=0)
print(batch_vec)
print(batch_vec.shape)

batch_vec = th.stack([vec1, vec2, vec3], dim=1)
print(batch_vec)
print(batch_vec.shape)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.Size([3, 3])
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])
torch.Size([3, 3])


In [ ]:
th.mean()
th.sum()
th.min()
th.argmin()
th.max()
th.argmax()

# 퀴즈 (Hard)
1) 길이가 4096인 랜덤벡터를 하나 생성하세요.  
2) 벡터를 위에서 배운 메소드들 중 하나를 이용해 (64x64) 정사각행렬로 차원을 조정하세요.  

3) 1, 2의 과정을 반복해서 정사각행렬을 세 개 만든다음, 각각 텐서의 0번째 축에 크기가 1인 잉여차원을 추가하세요.  
4) 0번째 축과 마지막 축을 교환하세요.   
5) 리스트에 세 개의 정사각행렬을 담아서 마지막 축을 기준으로 텐서를 합성하세요 -> 64x64x3 텐서가 나와야함  
6) 위의 과정을 4번 반복해서 64x64x3 를 쌓아서 4 x 64 x 64 x 3 텐서를 만드세요  

In [95]:
th.manual_seed(1030)
# code : 